### ISSUE TITLE
Depends on Cachex if only Nebulex will be used.

### ISSUE THREAD

**Issue by rhblind** [vheathen/commanded-uniqueness-middleware#20]
Hi, 
I'm having problems compiling this library because it seems that `Chachex` is a required dependency when even though I'll use the `Commanded.Middleware.Uniqueness.Adapter.Nebulex` adapter.

I understand why but it seems like `Cachex` is listed as an optional dependency, which seems to be incorrect in this case. 

Traceback
```shell
== Compilation error in file lib/commanded/middleware/uniqueness/adapter/nebulex.ex ==
** (CompileError) lib/commanded/middleware/uniqueness/adapter/nebulex.ex:6: module Cachex.Spec is not loaded and could not be found. This may be happening because the module you are trying to load directly or indirectly depends on the current module
```

**Comment by vheathen** [comment]
Sorry for such a late reply, for some reason I don't receive notifications about new issues.

Yes, you are absolutely correct, `cachex` and `nebulex` dependencies should not be optional as without any of them it is not possible to build the whole library. A solution could be to move adapters out to their own packages, but it will take some time.
Also, there is a bug in the code which does not affect the behaviour but of course - nebulex adapter shouldn't require Cachex.Spec - it's an artefact.

For now, I'll remove `optional` flags from both `cachex` and `nebulex` and remove `Cachex.Spec` from the nebulex adapter. And some time later I will move adapters out of the library so it will be possible to have only necessary dependencies.
