### ISSUE TITLE
Add Nebulex adapter

### ISSUE THREAD

**Issue by vheathen** [vheathen/commanded-uniqueness-middleware#9]
As [nebulex](https://github.com/cabol/nebulex) supports dynamic clusters without static node list in config it can be more suitable in some environments.

From stack**overflow** [answer](https://stackoverflow.com/a/55425225):

> I looked at this for my day job a while back and Cachex doesn't have a solution for dynamic node membership. It expects you to have all of your node names predefined and static. You can do this in Kubernetes with stateful sets, but you'll throw away all future possibility of autoscaling if you want to keep your cache distributed across all nodes.
> 
> A better solution IMO is Nebulex. Nebulex is not concerned about managing the connection to your nodes or their membership. It is only concerned with keeping a cache distributed across [Node.self() | Node.list()] (all of the nodes in your cluster). It all runs over PG2 which is a distributed pubsub implementation. It has the ability to transfer data as nodes join or leave and will shard it so that you have duplicate data across your nodes. It even allows you to match on node names to store your cached data.

**Comment by AHBruns** [comment]
So, this is a blocker for my usage of this library as my work does constant rolling deploys, and we need a hard guarantee of uniqueness even in the face of that. For now, I plan to implement a poor man's solution via a database table with a uniqueness constraint + a recurring job which constantly cleans up records after a given TTL, but I'd much prefer a lighter solution like Nebulex. If you're still maintaining this library, let me know and I'll look into adding this adpater.

**Comment by vheathen** [comment]
> If you're still maintaining this library, let me know and I'll look into adding this adpater.

Thanks a lot, @AHBruns , I still maintain the library. I didn't get enough time to deal with Nebulex, so you are very welcome.
